name: reusable workflow
on:
  workflow_call:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo job 1
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo job 2
