name: reusable workflow
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      inp1:
        type: branch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo job 1 -- ${{ github.ref }}
      - run: echo 1. form j1 >> "$GITHUB_STEP_SUMMARY"
      - run: 'printf "ansi escape: \33[31in read\nnext line\n"'
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo job 2
      - run: echo 1. form j2 >> "$GITHUB_STEP_SUMMARY"
      - run: echo runner name = $RUNNER_NAME >> "$GITHUB_STEP_SUMMARY"
      - run: echo '## title from job 2' >> "$GITHUB_STEP_SUMMARY"
